// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-qoqMbLIYtX3WegKt1u3kWW2dWFDeiYw',
    appId: '1:847289801888:web:a0a52f2a1aff2b87917dc5',
    messagingSenderId: '847289801888',
    projectId: 'music-player-3e7d8',
    authDomain: 'music-player-3e7d8.firebaseapp.com',
    storageBucket: 'music-player-3e7d8.firebasestorage.app',
    measurementId: 'G-XXJP2HM4DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnXqRGtN7Nr-W3W2gQ7YX-Rn0a9hy14yg',
    appId: '1:847289801888:android:8f1005ee70daf1a2917dc5',
    messagingSenderId: '847289801888',
    projectId: 'music-player-3e7d8',
    storageBucket: 'music-player-3e7d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFxfo10bY7_yYO6qFSKCvFtKEGOLnoaJM',
    appId: '1:847289801888:ios:df20df085a84bb1c917dc5',
    messagingSenderId: '847289801888',
    projectId: 'music-player-3e7d8',
    storageBucket: 'music-player-3e7d8.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFxfo10bY7_yYO6qFSKCvFtKEGOLnoaJM',
    appId: '1:847289801888:ios:df20df085a84bb1c917dc5',
    messagingSenderId: '847289801888',
    projectId: 'music-player-3e7d8',
    storageBucket: 'music-player-3e7d8.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-qoqMbLIYtX3WegKt1u3kWW2dWFDeiYw',
    appId: '1:847289801888:web:4abbff1c1ddd9cc4917dc5',
    messagingSenderId: '847289801888',
    projectId: 'music-player-3e7d8',
    authDomain: 'music-player-3e7d8.firebaseapp.com',
    storageBucket: 'music-player-3e7d8.firebasestorage.app',
    measurementId: 'G-MTDSP10P6T',
  );
}
